### ISSUE TITLE
Eliminacja autoryzacji

### ISSUE THREAD

**Issue by areknoster** [pw-software-engineering/specification#2]
W tym issue chciałbym przedyskutować eliminację autoryzacji, celem zwężenia scope projektu.

Na ogół widzę 3 możliwości podejścia do problemu:
1. Pozostawienie tak, jak jest
2. Usunięcie autoryzacji, ale pozostawienie samego użytkownika.
Zaleta: większość logiki poza samą autoryzacją pozostaje bez zmian
Wada: scope projektu niewiele się zmniejsza. Nadal musimy jakoś tego użytkownika ustawiać (może być samo ID z ciasteczka), nadal musimy go przesyłać i trzymać go w bazie danych. Nadal utrzymujemy całą logikę związaną z dostosowaniem treści dla danego użytkownika (czy dana kontrolka ma się wyświetlić? czy dana operacja jest dozwolona?)
3. Radykalne: usunięcie użytkownia jako takiego - robimy projekt tak, jakby istniał tylko jeden admin, jeden hotelarz i jeden klient, którzy mogą robić "wszystko" w danym panelu. 

Osobiście jestem zwolennikiem 3. opcji. Taka zmiana radykalnie zmniejszyłaby liczbę zależności (niemal wszystkie operacje zależą od użytkownika). Dodatkową zaletą jest to, że uproszczenie to w równym stopniu dotyczyłoby wszystkich trzech modułów. Wydaje mi się, że ze względu na rozmiar projektu, ograniczenie czasowe i brak naszego doświadczenia, lepiej zrobić dużo mniej, a dobrze przetestowanego i działającego.

**Comment by mtabor99-pw** [comment]
Co do autoryzacji klient-serwer, wydaje mi się, że opcja 2. byłaby najlepsza z kilku względów. Wyodrębnienie tylko jednego klienta i hotelu brzmi kusząco, ale wydaje mi się że jest do dość duże uproszczenie w logice.

Kwestię poprawy autoryzacji _klient - serwer_ widziałbym następująco:
Logowanie odbywałoby się za pomocą endpoint'u **/client/login**, czyli tak jak obecnie. Przekazywany jest login i hasło a zwracany JSON z informacjami jak ID klienta równym ID rekordu w tabeli, w której serwer przetrzymuje wszystkich użytkowników. Swoją drogą, rejestracja by polegała na wpisaniu przez administratora do tej bazy danych nowego rekordu i tyle. Następnie taki obiekt JSON byłby przesyłany jako ciasteczko (nie jako header i bez żadnej enkrypcji żeby uprościć cały proces), po czym serwer serwer sprawdzałby czy istnieje to ciasteczko w celu przeprowadzenia autentykacji i autoryzacji w oparciu o właściwość ID obiektu JSON w tym ciasteczku (dokładna specyfikacja tego obiektu JSON na razie nie jest tutaj kluczowe - jedynie istotne jest to że zawierałby on taką właściwość z ID klienta). W takim scenariuszu wydaje mi się, że ten proces "autentykacji i autoryzacji" w porównaniu do rozwiązania 3. różniłby się jedynie małym fragmentem kodu, który by sprawdzał czy jest to ciasteczko i tyle. Co do następującej kwestii: 

> czy dana kontrolka ma się wyświetlić? czy dana operacja jest dozwolona?

Wszystkie akcje dzieją się za pomocą API, którego **wszystkie** endpointy są zabezpieczone oprócz endpoint'a związanego z logowaniem. Więc w zasadzie jedyna strona do jakiej miałby dostęp niezalogowany klient to strona główna z logowaniem. Odwiedzenie jakiejkolwiek innej strony wiązało by się z błędem 403 i tyle.

**Comment by mtabor99-pw** [comment]
> (nie jako header i bez żadnej enkrypcji żeby uprościć cały proces),

Odnośnie mojego poprzedniego komentarza: W celu uproszczenia systemu prościej chyba przyjąć koncepcję, że ten obiekt JSON byłby przesyłany w nagłówku a nie jako ciasteczko - po pierwsze nie trzeba zbytnio zmieniać specyfikacji a po drugie (wydaje mi się) jest to prostsza rzecz do implementacji niż ciasteczka.
