### ISSUE TITLE
[ZMIANA] System opinii

### ISSUE THREAD

**Issue by mtabor99-pw** [pw-software-engineering/specification#26]
Chciałbym poruszyć kwestię opinii tworzonych przez klientów. Na chwile obecną klient może tworzyć opinię w momencie, gdy odbył jakąś rezerwację w ramach oferty (rezerwacja nie została anulowana i się zakończyła). Ponadto zostało przyjęte założenie, że klient może wystawić tylko 1 opinię w ramach oferty (może ją później usunąć/edytować). Chciałbym jednak zaproponować zmianę tego systemu t.j. umożliwić wystawianie wielu opinii w ramach jednej oferty - po jednej opinii na każdą rezerwację (oczywiście nadal przy założeniu, że ta rezerwacja jest ukończona i wystawianie opinii jest opcjonalne). Wydaje mi się, że ma to większy sens, np. w przypadku gdy ktoś zrobi rezerwację wielokrotnie i przy pierwszym pobycie stwierdzi, że coś mu się nie podobało a przy drugim pobycie np. rok później stwierdzi, że wszystko jednak się poprawiło (albo pogorszyło). W obecnym systemie można wystawić tylko jedną opinię na ofertę, więc trudno jest zrealizować przypadek wyżej opisany (niby zawsze można zrobić tak by "upakować" więcej informacji w jedną opinię, ale jak dla mnie to jest najgorsze rozwiązanie).
W związku z tym, jeśli ta koncepcja zostanie przyjęta, należałoby zrobić następujące zmiany:
- w endpoint'cie `/client/reservations` zwracane informacje powinny być następujące:
```
  [
    {
      "hotelInfoPreview": {
        "hotelID": int,
        "hotelName": string,
        "country": string,
        "city": string
      },
      "reservationInfo":  {
        "reservationID": int,
        "from": datetime,
        "to": datetime,
        "numberOfChildren": int,
        "numberOfAdults": int,
        "reservationReviewID": int? (optional - present if there is no client review for an offer)
      }
      "offerInfo": {
        "offerID": int,
        "offerTitle": string,
      }
    }
  ]
```
W przypadku, gdy byłoby wiele rezerwacji informacje o hotelu i oferty rzeczywiście byłyby powielane, jednak wydaje mi się, że byłoby to akceptowalne ze względu na fakt, że warto by było udostępnić page'ing tego endpointa. Wówczas liczba zwracanych rezerwacji byłaby na tyle mała, że potencjalne powielanie informacji byłoby pomijalnie małe. Ponadto taki wariant jest prosty do implementacji w przeciwieństwie to tworzenia specjalnie obiektów "hotelInfo", w których zagnieżdżane są wszystkie związane z nim oferty "offerInfo" i w tych "offerInfo" z kolei znowu zagnieżdżone rezerwacje związane z danym numerem strony.
Warto tutaj wspomnieć, że w tym nowym schemacie wiadomości informacja o opinii jest związana z rezerwacją, więc w obiekcie "reservationInfo" znajduje się nowa właściwość "reservationReviewID". W obiekcie "offerInfo" byłby zwracany dodatkowo tytuł oferty żeby w UI móc wyświetlić użytkownikowi informacje o ofercie, w ramach której była zrobiona rezerwacja. Czy według was powinien być zwracany jeszcze np. "offerPreviewPicture" czy nie? Ja nie mam tutaj mocnego zdania akurat.
- Logika związana z tworzeniem i usuwaniem opinii powinna być chyba przeniesiona do jednego endpoint'a `/client/reservations/{reservationID}/review` z metodami GET, POST i DELETE (ewentualnie PATCH jeśli byśmy chcieli umożliwić modyfkowanie opinii). Chyba nie jest potrzebny sufiks typu "/review/{reviewID}" to w kontekście jednej rezerwacji jest zawsze jedna opinia. Kwestia błędów wyglądała by tak, że 404 byłby wysyłany w przypadku gdy w ramach rezerwacji nie istniałaby opinia, 403 w przypadku gdy odwołujemy się do {reservationID}, które nie jest nasze i 400 w przypadku POST (i ewentualnie PATCH) jeśli ciało zapytania HTTP miałoby błędny format. Tutaj można by się od razu zastanowić nad tym, żeby klient nie mógł wystawić/usunąć/edytować opinii po np. tygodniu od ukończenia rezerwacji, ale to jest rzecz drugorzędna w tym wszystkim.
- Wydaje mi się, że z perspektywy klienta wygodne byłoby oglądanie opinii dotyczących wszystkich ofert danego hotelu już z poziomu strony wyświetlającej szczegółowe informacje o hotelu (jak dotąd klient musiałby wejść na konkretną ofertę by zobaczyć jakiekolwiek opinie a tak to mógłby zobaczyć już wszystkie opinie związane z hotelem posortowane np. ze względu na datę ich wystawienia). Taki endpoint mógłby mieć nazwę `/hotels/{hotelID}/reviews` i byłby page'owany a zwracane przez niego dane byłyby w zasadzie identyczne jak w przypadku `/hotels/{hotelID}/offers/{offerID}/reviews`, tylko w ciele wiadomości zawarta byłaby dodatkowo informacja o tytule oferty i ID oferty (na wszelki wypadek by móc go użyć jakoś z poziomu UI):
```
  [
    {
      "reviewID": int,
      "content": string,
      "rating": int,
      "creationDate": datetime,
      "reviewerUsername": string,
      "offerID": int,
      "offerTitle": string
    }
  ]
```

Co sądzicie o takim nowym systemie?

**Comment by daveedoo** [comment]
Podsumowując:

-- tracimy to, że endpoint jest "elegancki". Informacje się powtarzają w ramach wielu zwracanych w tablicy obiektów (wyróżnikiem obiektu jest pole `reservationInfo`, które nigdy się nie powtarza wewnątrz tablicy).
Potencjalnie nawet wszystkie zwracane obiekty różnią się wyłącznie polem `reservationInfo`. Moim zdaniem kwestia pagingu nie rozwiązuje problemu, tylko go ukrywa.
Zastanawiam się natomiast, czy to rzeczywiście takie istotne. Alternatywnie moglibyśmy zamiast `hotelInfoPreview` dać samo `hotelID`, a zamiast `offerInfo` – `offerID`. Tak czy siak musielibyśmy wtedy ściągnąć te informacje z innych endpointów; powinniśmy dać klientowi możliwość pobrania tych informacji.
Chętnie posłuchałbym innych opinii.

++ możemy tworzyć wiele opinii w ramach tej samej oferty. Opinia nie jest już związana z ofertą, a z daną rezerwacją - sensownie. Bliższe rzeczywistości :)

++ możliwość wypisania wszystkich opinii już przy wyświetlaniu hotelu.

Jak dla mnie zmiana generalnie na +.

**Comment by cangi75** [comment]
Jeśli już chcemy zmieniać coś w systemie a propo endpointów dotyczących opini klinetów to w moim mniemanu najlepiej wrucić do pomysłu 1 opinia do 1 rezerwacji wydaje mi się to najbardziej logiczne z punktu widzenia tego co system ma robić.
```yaml
/client/reservations/{reservation_Id}/review
  get:
    description: Pobiera opinię do danej rezerwacji
    responses:
      200:
        body:
          
            application/json: 
               type: |
                  {
                    "reviewID": int,
                    "content": string,
                    "rating": int,
                    "creationDate": datetime,
                    "reviewerUsername": string
                  }
      401:
      404:
post:
    description: Creates a new review related to an offer
    body:
      application/json:
        type: |
          {
            "content": string,
            "rating": int,
          }
  put:
    description: Edits a client review related to an offer
    body:
      application/json: 
        type: |
                  {
                    "reviewID": int,
                    "content": string,
                    "rating": int,
                    "creationDate": datetime,
                    "reviewerUsername": string
                  }
                
      responses:
        200:
        401:
          description: Error related to an attempt of review edition without it's ownership
        404:
          description: Resource not found: there is no hotel with ID equal to hotelID that has an offer with ID equal to offerID or target review does not exist/is not related to the offer
  delete:
      description: Deletes a client review related to an offer
      responses:
        200:
        401:
          description: Error related to an attempt of review deletion without it's ownership
        404:
          description: Resource not found: there is no hotel with ID equal to hotelID that has an offer with ID equal to offerID or target review does not exist/is not related to the offer
 
```
wyglądało by to wtedy mniej więcej tak

**Comment by areknoster** [comment]
Podoba mi się propozycja @cangi75 , z tą jedną uwagą, że chyba moglibyśmy się całkowicie pozbyć metody post z tego kodu - wtedy put po prostu ustawiałby recenzję, niezależnie, czy istnieje czy nie

**Comment by mtabor99-pw** [comment]
Ok, to w takim wypadku do specki byłyby wprowadzone następujące zmiany (oprócz nowej koncepcji opinii oczywiście):
- informacje zwracane z endpoint'a `client/reservations` mają nowy format:
```
  [
    {
      "hotelInfoPreview": {
        "hotelID": int,
        "hotelName": string,
        "country": string,
        "city": string
      },
      "reservationInfo":  {
        "reservationID": int,
        "from": datetime,
        "to": datetime,
        "numberOfChildren": int,
        "numberOfAdults": int,
        "reservationReviewID": int? (optional - present if there is no client review for an offer)
      }
      "offerInfoPreview": {
        "offerID": int,
        "offerTitle": string,
        "offerPreviewPicture": file,
      }
    }
  ]
Ponadto endpoint ten (dla GET) będzie pageowany w takim stylu jak wszystkie inne endpointy [is.pageable].
```
(Uwaga - dodane jest pole `offerPreviewPicture`; wydaje mi się, że w założenie preview picture dość mało waży, a jednak da możliwość zrobienia ładniejszego UI przy przeglądaniu rezerwacji)
- nowy endpoint `/client/reservations/{reservationID}/review`:
```
/client/reservations/{reservation_Id}/review
  get:
    description: Pobiera opinię do danej rezerwacji
    responses:
      200:
        body:
            application/json: 
               type: |
                  {
                    "reviewID": int,
                    "content": string,
                    "rating": int,
                    "creationDate": datetime,
                    "reviewerUsername": string
                  }
      404:
        description: Reservation not found
  put:
    description: Creates/edits a new review related to an offer
    body:
      application/json:
        type: |
          {
            "content": string,
            "rating": int,
          }                
      responses:
        200:
        404:
  delete:
      description: Deletes a client review related to an offer
      responses:
        200:
        404:
```
Endpoint `/hotels/{hotelID}/offers/{offerID}/reviews/{reviewID}` oraz endpoint `POST /hotels/{hotelID}/offers/{offerID}/reviews` zostanie usunięty na rzecz nowego endpoint'a
- nowy endpoint `/hotels/{hotelID}/reviews`:
```
/hotels/{hotelID}/reviews:
  get:
    [is.pageable]
    description: Returns all reviews related to an offer
    responses:
      200:
        body:
          application/json:
            description: An arry of objects containing information related to offer reviews
            type: |
              [
                {
                  "reviewID": int,
                  "offerID": int,
                  "offerTitle": string,
                  "content": string,
                  "rating": int,
                  "creationDate": datetime,
                  "reviewerUsername": string
                }
              ]
      404:
        description: Hotel not found
```
Jak wspomniałem na początku, wydaje mi się, że endpoint ten daje możliwość zobaczenia opinii na temat różnych ofert co może być atrakcyjne z punktu UI i klienta, który chciałby przeczytać coś ogólnie o hotelu, np. najnowsze opinie dotyczące różnych ofert. Ponadto wydaje mi się, że implementacja takiego endpointa nie powinna być trudna - jest to prawie identyczny endpoint jak `/hotels/{hotelID}/offers/{offerID}/reviews`.
