### ISSUE TITLE
Bezpośredni dostęp do recenzji użytkownika

### ISSUE THREAD

**Issue by Gloomwidow** [pw-software-engineering/specification#28]
W obecnej specyfikacji za pomocą endpointu ` [GET] /reservations` możemy otrzymać listę rezerwacji użytkownika wraz z ID recenzji przypisanych do nich. Problem jest taki, że mimo tego, że mamy dostęp do ID, nie możemy bezpośrednio pobrać treści tej recenzji, co może się przydać np. przy dodawaniu możliwości edycji.

W obecnej chwili jedynym sposobem na uzyskanie treści szukanej recenzji, posiadając jej ID, jest wywołanie metody `[GET] /hotels/{hotelID}/offers/{offerID}/reviews`, a następnie wyszukanie jej na podstawie posiadanego ID z poprzedniego endpointu, co według mnie:

1. Będzie wymagało napisania wyjątkowo nieczytelnego rozwiązania, najprawdopodobniej po stronie front-endu.
2. Będzie nieoptymalne - pobieranie całej listy recenzji tylko po to, by odszukać jedną konkretną na pewno jest niewydajne. 

Co do rozwiązania tego problemu, proponuję wprowadzić do specyfikacji endpoint `[GET] /reviews/{reviewId}`, który by zwracał na podstawie Id recenzję danego użytkownika, o ile taka istnieje. Przykładowo:
```
/reviews/{reviewId}:
  get:
    description: Returns review with reviewId, provided that it exists and belongs to currently logged user
    responses:
      200:
        body:
          application/json:
            description: An object containing content of requested review
            type: |
                {
                  "reviewID": int,
                  "content": string,
                  "rating": int,
                  "creationDate": datetime,
                  "reviewerUsername": string
                }
                |
      404:
        description: Resource not found: e.g. there is no review with provided reviewId or logged user wasn't the author of that review
```
Taki endpoint na pewno ułatwi wszystkich zespołom pracę nad implementacją możliwości edycji ocen.

**Comment by mtabor99-pw** [comment]
Prosiłbym o przejrzenie #26 (oraz #27) i nowej wersji client-endpoints.raml . Zamieściłem tak w końcu zmiany z #26 oraz #27, które w zasadzie zawierają tą zmianę, o której mowa w tym "issue" (tylko pod endpointem `GET /client/reservation/{reservationID}/reviews`)
