### ISSUE TITLE
Dostęp do ID w enpoincie [GET] /offers

### ISSUE THREAD

**Issue by Gloomwidow** [pw-software-engineering/specification#29]
W danym momencie z endpointa `[GET] /offers` po stronie hotelu możemy uzyskać dane oferty, ale nie mamy dostępu do ID oferty, co właściwie uniemożliwia zaimplementowanie po stronie front-endu funkcji wymagających ID oferty (np. edycja oferty za pomocą `[PATCH]/offers/{offerID}`). 

Najprościej będzie dodać do struktury `offerPreview` pole `offerID`, które będzie przekazywane wraz z endpointem `[GET] /offers`. Dzięki temu przy implementowaniu następnych funkcjonalności możemy wykorzystać to ID do operacji związanych z konkretną ofertą z listy ofert.

**Comment by daveedoo** [comment]
Powinno być tak, jak piszesz. Dodamy fix do specyfikacji, dzięki!
