### ISSUE TITLE
Podział DataManager

### ISSUE THREAD

**Issue by areknoster** [pw-software-engineering/specification#3]
Proponuję podział ogromnej klasy ServerManager na mniejsze, które mogą działać niezależnie od siebie. Podział, który bym widział to:
1. `ReviewService`
2. `OfferService`
3. `ReservationService`
Każda z tych klas miałaby odpowiedni interface z metodami  obecnie należącymi do `ServerManager`, a `DataManager` byłby skomponowany z powyższych.

Zmiana ta bardzo uprościłaby cały moduł serwerowy i znacznie ułatwiła testowanie oraz podział zadań do implementacji.

**Comment by cangi75** [comment]
chodzi ci o taki podział mniej więcej?
![Untitled Diagram](https://user-images.githubusercontent.com/61029787/109862148-62218280-7c60-11eb-970c-5ad154b37571.png)

i czy taki podział jest ok @mtabor99-pw ?

**Comment by mtabor99-pw** [comment]
Jak dla mnie podział na te serwisy jest jak najbardziej dobry - uważam natomiast, że nie jest to aż tak istotne dla specyfikacji, gdyż temat jest bardziej związany z architekturą wewnętrzną związaną z implementacją konkretnego jednego modułu (tutaj modułu serwera). Kwestia wewnętrznej architektury modułów i jej implementacji jest według mnie problemem, z którym każdy zespół oddzielnie będzie musiał się zmagać.
To powiedziawszy, zaproponowane przez @cangi75 rozbicie modułu serwerowego na serwisy będzie uwzględnione w kolejnych wersjach specyfikacji (oczywiście kwestia kolejnych poprawek tych klas reprezentujących serwisy jest cały czas otwarta)
