### ISSUE TITLE
Uzupełnienie co do stronicowania

### ISSUE THREAD

**Issue by Gloomwidow** [pw-software-engineering/specification#32]
Czyli co do stron i obsługi błędów związanych ze stronicowaniem umawiamy się na taką konwencję:
Strona <=0  zwraca Bad Request
Strona dalsza niż ilość stron zwraca pustą albo ostatnią stronę

**Comment by mtabor99-pw** [comment]
Tak, numer strony <= 0 lub liczba rekordów na stronę <= 0 powinna rzucać Bad Request'a. Jeśli poda się stronę o takim numerze, że zabraknie rekordów bo wyświetlenia to zwracana jest pusta strona (albo ostatnia, jak kto woli)
