### ISSUE TITLE
Uzupełnienie informacji co do avaibilityTimeIntervals

### ISSUE THREAD

**Issue by Gloomwidow** [pw-software-engineering/specification#33]
Czy moglibyście uzupełnić informację w jaki sposób hotel może uzupełniać możliwe daty rezerwacji w polach availabilityTimeIntervals dotyczących ofert? Z tego co widzę specyfikacja nie podaje żadnego endpointa lub sposobu na to, by te daty uzupełnić.

**Comment by mtabor99-pw** [comment]
Ogólnie to zmieniona została na początku semestru koncepcja dotycząca tego kto przechowuje dane dotyczące rezerwacji i pokoi hotelowych. Na początku hotel miał mieć swoją bazę danych gdzie te informacje byłyby przechowywane i na podstawie tych danych miał wyznaczać te availabilityTimeIntervals i je wysyłać do serwera (o to chodziło z tą synchronizacją). Ustaliliśmy jednak, że w celu zmniejszenia scope projektu przeniesiemy dane o rezerwacjach i pokojach całkowicie do serwera - wówczas serwer sam w oparciu o te dane wyznacza przedziały dostępności w momencie gdy klient wysyła żądanie o szczegóły oferty. Czyli podsumowując - endpointa nie ma, bo ostatecznie zdecydowaliśmy się na to, żeby serwer sam wyznaczał te przedziały, bo na serwerze są przechowywane dane dotyczące pokoi hotelowych.
