### ISSUE TITLE
Uzupełnienie informacji co do rezerwacji

### ISSUE THREAD

**Issue by Gloomwidow** [pw-software-engineering/specification#34]
Czy moglibyście uzupełnić informację w jaki sposób rezerwację są łączone z pokojami w ofertach? Endpoint hotelu `/reservations` podaje informacje o połączeniu pokoju z rezerwacją, a dokumentacja w żaden sposób tego tematu nie porusza.

Czy dobrze rozumiem, że podczas tworzenia rezerwacji jest przypisywany pierwszy dostępny pokój z oferty, a jeżeli takich pokoi nie ma, to ta rezerwacja jest odrzucana?

**Comment by mtabor99-pw** [comment]
Jeśli chodzi o to w jaki sposób jest dopasowywany pokój do rezerwacji to jest tutaj dowolność - przyjęty algorytm dopasowania pokoi nie wpływa na kontrakt związany z komunikacją między modułami. Można więc tutaj zrealizować to na wiele sposobów, np. znajdując pierwszy dostępny pokój w terminie i tyle (albo jakoś inaczej jeśli ma się pomysł na bardziej optymalny algorytm)
