### ISSUE TITLE
Synchronizacja

### ISSUE THREAD

**Issue by areknoster** [pw-software-engineering/specification#4]
Mam problem ze zrozumieniem, dlaczego 
```
Informacje o rezerwacji są przechowywane zarówno w bazie danych modułu hotelowego jak i modułu serwera.
```
Tworzy to całą dużą klasę problemów, o których można by napisać książkę lub dwie. Dodatkowo do synchronizacji danych pomiędzy tymi modułami został stworzony cały protokół komunikacji. Generalnie z mojego osobistego doświadczenia - to będzie bardzo trudne.

Moja propozycja, jak to uprościć:
1. Wszystkie dane umieścić w module serwerowym, moduł hotelowy tylko wysyła zapytania o nie
2. Cała komunikacja, zamiast skomplikowanego, customowego i niskopoziomowego protokołu, zrealizować za pomocą GRPC. 
Krótko co to GRPC: https://www.youtube.com/watch?v=XRXTsQwyZSU
W C#: https://grpc.io/docs/languages/csharp/quickstart/
Myślę, że jest to dużo mniej skomplikowane, niż obecny model komunikacji modułu hotelowego z serwerowym. 

Więc jak by wyglądała zamiana obecnej komunikacji na GRPC?
1. Piszemy schemę (mogę nawet ja to zrobić na podstawie obecnie zdefiniowanej komunikacji)
2. Każdy sobie na jej podstawie generuje zestawy klient-serwer. Do serwera trzeba zaimplementować i zinjektowac logikę, która realizuje daną funkcję.
3. voila, możemy wywoływać za pomocą klienta metody na serwerze!

Dodatkowo, ta schema załatwiłaby nam całą dokumentację, jeśli chodzi o komunikację moduł hotelowy-serwerowy.

**Comment by mtabor99-pw** [comment]
Faktycznie,

> Informacje o rezerwacji są przechowywane zarówno w bazie danych modułu hotelowego jak i modułu serwera.

jest dość mało sensowne w dosłownym znaczeniu. Ogólnie cała synchronizacja polega na tym, że po stronie serwera przechowywane są w bazie danych interwały czasowe, w których dana oferta nie jest dostępna. Informacja o braku dostępności danej oferty jest otrzymywana od hotelu, t.j. hotel na podstawie swojej bazy danych i tego jakie pokoje w ramach oferty są zarezerwowane na jakie okresy czasowe, może przekazać te informacje o niedostępności oferty do serwera. Zamysł tego jest taki, że dzięki takiemu mechanizmowi, serwer wie tylko czy można zrobić rezerwację danej oferty w danym przedziale czasowym (i obowiązkiem hotelu jest synchronizowanie tych informacji), natomiast obowiązkami hotelu jest już zarządzanie tymi rezerwacjami i przyporządkowanie tych rezerwacji do odpowiednich pokoi hotelowych. Ponadto dzięki takiemu systemowi hotel może w dowolnym momencie przeorganizować przyporządkowanie rezerwacji do pokoi i udostępnić daną ofertę na nowy przedział czasowy dzięki takiemu przeorganizowaniu.
Czyli podsumowując - hotel trzyma dane o rezerwacjach, na podstawie których przyporządkowuje odpowiednie pokoje do rezerwacji, natomiast serwer przetrzymuje dane o niedostępności ofert oraz dane o rezerwacjach, które spełniają bardziej funkcję informacyjną dla klienta, że zrobił rezerwację w danym czasie, hotelu itp.
W efekcie cała synchronizacja odbywa się jedynie w 2 przypadkach:
1. Serwer "spontanicznie" zażąda synchronizacji z hotelem (jak na razie w specyfikacji nie ma dokładnie w jakich warunkach serwer może zażądać synchronizacji - chodziło tutaj o umożliwienie takiego mechanizmu np. gdyby chciało się zaimplementować periodycznej synchronizacji, czy mechanizmu synchronizacji w oparciu o jakiej statystyki)
2. Hotel żąda synchronizacji z serwerem ze względu na to, że serwer stwierdził w oparciu o lokalne dane, że rezerwacja może być zrobiona, ale w hotelu coś się w między czasie zmieniło i już nie jest możliwe utworzenie rezerwacji
3. Hotel "spontanicznie" zażąda synchronizacji z serwerem (sytuacja ze "spontanicznością" jak wyżej)
4. Po usunięciu rezerwacji przez klienta zwolni się jakiś termin oferty, co zostanie wykryte przez hotel - wówczas przesyłane jest żądanie synchronizacji w celu powiadomienia serwera o fakcie, że oferta jest dostępna w nowym przedziale czasowym

Czy to bardziej wyjaśnia nasz zamysł "synchronizacji" i czy nadal byłyby proponowane wspomniane przez @areknoster zmiany?

**Comment by cbanach** [comment]
Również uważam że prowadzenie równoległych baz danych generuje klasę problemów, jednocześnie nie zwiększając istotnie możliwości systemu (opisana przez @mtabor99-pw funkcjonalność może być realizowana w całości na serwerze). Gdybyście uznali że jest to jednak konieczne, popierałbym @areknoster w wymianie TCP na jakiś wysokopoziomowy protokół, może być zaproponowany wczesniej gRCP (nie mam z nim doświadczenia) albo zwykły REST po HTTP.
