### ISSUE TITLE
Moduł hotelowy - system uprawnień użytkowników

### ISSUE THREAD

**Issue by j-janiszewski** [pw-software-engineering/specification#9]
Tutaj chciałbym przedyskutować podział na uprawnienia użytkowników korzystających z hotelu: czyli Menadżera hotelu oraz Obługe hotelową. Wydaję mi się, że podział ten nie jest kluczowy dla działania systemu i jest to jedna z rzeczy z których możemy zrezygnować w celu ograniczenia złożoności projektu.

**Comment by mtabor99-pw** [comment]
Nasz zespół ustalił, że kwestia pracowników hotelu i systemu uprawnień jest rzeczywiście zbędna. W obecnej wersji specyfikacji nie powinno być już wymagań dotyczących obsługi hotelu (jeśli jest, to proszę o powiadomienie naszego zespołu). Ostatecznie stanęło na tym, że moduł hotelowy jest pojedynczą aplikacją z interfejsem użytkownika, do którego dostęp ma z założenia jedynie manager hotelu (do dodawania/usuwania/edytowania ofert i opcjonalnie sprawdzania stanu rezerwacji w konkretnym dniu)

**Comment by cangi75** [comment]
Wszystko dotyczące pracowników zostało usunięte wczoraj poczynając od diagramów UML klas do końca dokumentu. Mogły zostać jakieś wzmianki wcześniej, ale to część specyfikacji odnosząca się do pomysłu (czytaj User stories itp). Mogę je z tamtąd usunąć, ale szczerze nie wydaje mi się to potrzebne.

**Comment by cangi75** [comment]
Zważyłem że nie usunąłem wzmianek do klas dotyczących employee z spisu treści. To już poprawiono
